(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/integralMall/createOrder/chooseAddress/chooseAddress"],{"52ab":function(t,a,e){},"8cba":function(t,a,e){"use strict";e.r(a);var n=e("abd6"),s=e.n(n);for(var i in n)"default"!==i&&function(t){e.d(a,t,(function(){return n[t]}))}(i);a["default"]=s.a},abd6:function(t,a,e){"use strict";Object.defineProperty(a,"__esModule",{value:!0}),a.default=void 0;var n={data:function(){return{data:{},list:[],layerFlag:!1}},components:{},props:{},beforeMount:function(){this.getList()},methods:{getList:function(){var t=this;this.http({url:"shopContact"}).then((function(a){console.log(a),t.setData({data:a.data[0],list:a.data}),t.$emit("addressid",{detail:{addressid:a.data[0].id}})}))},changeAddress:function(t){this.setData({layerFlag:!this.layerFlag})},chooseThis:function(t){console.log(this.list[t.currentTarget.dataset.index]),this.setData({data:this.list[t.currentTarget.dataset.index],layerFlag:!1}),this.$emit("addressid",{detail:{addressid:this.data.list[t.currentTarget.dataset.index].id}})}}};a.default=n},b098:function(t,a,e){"use strict";var n,s=function(){var t=this,a=t.$createElement;t._self._c;t._isMounted||(t.e0=function(t){return t.stopPropagation(),(!1)(t)})},i=[];e.d(a,"b",(function(){return s})),e.d(a,"c",(function(){return i})),e.d(a,"a",(function(){return n}))},e039:function(t,a,e){"use strict";var n=e("52ab"),s=e.n(n);s.a},e19d:function(t,a,e){"use strict";e.r(a);var n=e("b098"),s=e("8cba");for(var i in s)"default"!==i&&function(t){e.d(a,t,(function(){return s[t]}))}(i);e("e039");var r,d=e("f0c5"),o=Object(d["a"])(s["default"],n["b"],n["c"],!1,null,"2caf3b8c",null,!1,n["a"],r);a["default"]=o.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/integralMall/createOrder/chooseAddress/chooseAddress-create-component',
    {
        'pages/integralMall/createOrder/chooseAddress/chooseAddress-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("e19d"))
        })
    },
    [['pages/integralMall/createOrder/chooseAddress/chooseAddress-create-component']]
]);
