(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/createOrder/tab/address/address"],{"3b80":function(t,a,e){},"4f18":function(t,a,e){"use strict";(function(t){Object.defineProperty(a,"__esModule",{value:!0}),a.default=void 0;getApp();var e={data:function(){return{data:{},willData:{},dataList:"",layerFlag:!1,background:t.getStorageSync("background"),nabigationFontColor:t.getStorageSync("nabigationFontColor")}},components:{},props:{show:{type:Boolean,default:!1},listname:{type:String},addressFlag:{type:String}},watch:{show:{handler:function(t){console.log("show",t),t&&this.getAddress()}},addressFlag:{handler:function(t){console.error(t),"到点自提"!=t&&this.getAddress()}}},beforeMount:function(){this.getAddress()},methods:{showlayer:function(t){this.setData({layerFlag:!this.layerFlag,willData:this.data})},willChoose:function(t){this.setData({willData:this.dataList[t.currentTarget.dataset.index]})},chooseAddress:function(){this.setData({layerFlag:!1,data:this.willData}),this.$emit("getaddress",{detail:this.data})},close:function(){this.setData({layerFlag:!1})},getAddress:function(){var t=this;this.http({url:"shopContact"}).then((function(a){t.setData({dataList:a.data,data:a.data[0]}),console.log("收货地址",t.data,a.data),t.$emit("getaddress",{detail:a.data[0]})})).catch((function(a){console.log("收货地址",a),t.setData({data:[]})}))},goCreatedAddress:function(){wx.navigateTo({url:"/pages/home/addAddress/addAddress"})}}};a.default=e}).call(this,e("543d")["default"])},"6a08":function(t,a,e){"use strict";e.r(a);var n=e("7697"),s=e("f3b9");for(var o in s)"default"!==o&&function(t){e.d(a,t,(function(){return s[t]}))}(o);e("6d31");var r,d=e("f0c5"),i=Object(d["a"])(s["default"],n["b"],n["c"],!1,null,"bf1a372a",null,!1,n["a"],r);a["default"]=i.exports},"6d31":function(t,a,e){"use strict";var n=e("3b80"),s=e.n(n);s.a},7697:function(t,a,e){"use strict";var n,s=function(){var t=this,a=t.$createElement;t._self._c},o=[];e.d(a,"b",(function(){return s})),e.d(a,"c",(function(){return o})),e.d(a,"a",(function(){return n}))},f3b9:function(t,a,e){"use strict";e.r(a);var n=e("4f18"),s=e.n(n);for(var o in n)"default"!==o&&function(t){e.d(a,t,(function(){return n[t]}))}(o);a["default"]=s.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/createOrder/tab/address/address-create-component',
    {
        'pages/createOrder/tab/address/address-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("6a08"))
        })
    },
    [['pages/createOrder/tab/address/address-create-component']]
]);
