(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/goodsItem/share/share"],{"24b7":function(e,t,n){"use strict";n.r(t);var o=n("bb9f"),a=n("9c61");for(var i in a)"default"!==i&&function(e){n.d(t,e,(function(){return a[e]}))}(i);n("adfe");var r,s=n("f0c5"),c=Object(s["a"])(a["default"],o["b"],o["c"],!1,null,"04bba0e2",null,!1,o["a"],r);t["default"]=c.exports},4016:function(e,t,n){},"9c61":function(e,t,n){"use strict";n.r(t);var o=n("b941"),a=n.n(o);for(var i in o)"default"!==i&&function(e){n.d(t,e,(function(){return o[e]}))}(i);t["default"]=a.a},adfe:function(e,t,n){"use strict";var o=n("4016"),a=n.n(o);a.a},b941:function(e,t,n){"use strict";(function(e){Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var n={data:function(){return{good_phenosphere_is_open:!1}},components:{},props:{shareFlag:{type:Boolean},goodsid:{type:Number},goodName:{type:String},bannerList:{type:Array},data:{type:Object}},watch:{goodsid:{handler:function(){},immediate:!0},goodName:{handler:function(){},immediate:!0},bannerList:{handler:function(){},immediate:!0,deep:!0}},beforeMount:function(){this.setData({good_phenosphere_is_open:e.getStorageSync("Config").good_phenosphere})},methods:{showShare:function(){this.$emit("showShare")},toshare:function(){wx.navigateTo({url:"/pages/share/share?id=".concat(this.goodsid,"&type=2&price=").concat(this.data.min_price)})},togoodsgroup:function(){wx.openBusinessView({businessType:"friendGoodsRecommend",extraData:{product:{item_code:this.goodsid,title:this.goodName,image_list:this.bannerList}},success:function(e){},fail:function(e){}})}}};t.default=n}).call(this,n("543d")["default"])},bb9f:function(e,t,n){"use strict";var o,a=function(){var e=this,t=e.$createElement;e._self._c},i=[];n.d(t,"b",(function(){return a})),n.d(t,"c",(function(){return i})),n.d(t,"a",(function(){return o}))}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/goodsItem/share/share-create-component',
    {
        'pages/goodsItem/share/share-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("24b7"))
        })
    },
    [['pages/goodsItem/share/share-create-component']]
]);
