(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/createOrder/tab/groupAddress/groupAddress"],{"0f67":function(a,e,t){"use strict";(function(a){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;getApp();var t={data:function(){return{bg:a.getStorageSync("background"),area_name:"",group:"",addr:"",avatar:"",address:"",name:a.getStorageSync("user").nickname,phone:a.getStorageSync("user").phone,leader_name:""}},components:{},props:{addresstype:{type:Number},flag:{type:Boolean},show:{type:Boolean,default:!1}},watch:{show:{handler:function(e){a.getStorageSync("area")&&e&&this.setData({area_name:a.getStorageSync("area").area_name||"",group:a.getStorageSync("area").realname,addr:a.getStorageSync("area").addr,avatar:a.getStorageSync("area").avatar,address:a.getStorageSync("area").addr})},immediate:!0}},beforeMount:function(e){this.setData({leader_name:a.getStorageSync("leader_name")})},destroyed:function(){console.log("我走了"),this.setData({area_name:"",group:"",addr:"",avatar:"",address:""})},methods:{go:function(a){wx.navigateTo({url:"/group/changegroup/changegroup/changegroup"}),this.setData({area_name:"",group:"",addr:"",avatar:"",address:""})},change:function(a){"name"==a.currentTarget.dataset.type?this.setData({name:a.detail.value}):"phone"==a.currentTarget.dataset.type?this.setData({phone:a.detail.value}):"address"==a.currentTarget.dataset.type&&this.setData({address:a.detail.value});this.name,this.phone,this.address}}};e.default=t}).call(this,t("543d")["default"])},"213d":function(a,e,t){},"85a6":function(a,e,t){"use strict";t.r(e);var r=t("f5fd"),n=t("bd82");for(var o in n)"default"!==o&&function(a){t.d(e,a,(function(){return n[a]}))}(o);t("c01f");var d,s=t("f0c5"),u=Object(s["a"])(n["default"],r["b"],r["c"],!1,null,"6522a226",null,!1,r["a"],d);e["default"]=u.exports},bd82:function(a,e,t){"use strict";t.r(e);var r=t("0f67"),n=t.n(r);for(var o in r)"default"!==o&&function(a){t.d(e,a,(function(){return r[a]}))}(o);e["default"]=n.a},c01f:function(a,e,t){"use strict";var r=t("213d"),n=t.n(r);n.a},f5fd:function(a,e,t){"use strict";var r,n=function(){var a=this,e=a.$createElement;a._self._c},o=[];t.d(e,"b",(function(){return n})),t.d(e,"c",(function(){return o})),t.d(e,"a",(function(){return r}))}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/createOrder/tab/groupAddress/groupAddress-create-component',
    {
        'pages/createOrder/tab/groupAddress/groupAddress-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("85a6"))
        })
    },
    [['pages/createOrder/tab/groupAddress/groupAddress-create-component']]
]);
