(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["superuser/userinfo/userContent/userContent"],{"0e0a":function(t,e,n){"use strict";(function(t){function n(t,e){var n=Object.keys(t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(t);e&&(r=r.filter((function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable}))),n.push.apply(n,r)}return n}function r(t){for(var e=1;e<arguments.length;e++){var r=null!=arguments[e]?arguments[e]:{};e%2?n(Object(r),!0).forEach((function(e){a(t,e,r[e])})):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(r)):n(Object(r)).forEach((function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(r,e))}))}return t}function a(t,e,n){return e in t?Object.defineProperty(t,e,{value:n,enumerable:!0,configurable:!0,writable:!0}):t[e]=n,t}Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var o={data:function(){return{avatar:t.getStorageSync("user").avatar,balance:0,data:{},is_leader:t.getStorageSync("user").is_leader,announcement:"",background:"#434959"}},components:{},props:{},beforeMount:function(){console.log("aaaa"),this.getData(),this.tuanLeader(),this.setData({background:"#434959"})},methods:{getData:function(){var t=this;this.http({url:"distributionCenter"}).then((function(e){console.log(e),t.setData({data:r({},t.data,{},e.data)})}))},tuanLeader:function(){this.setData({data:t.getStorageSync("user")})},go:function(t){console.log(),wx.navigateTo({url:t.currentTarget.dataset.url})}}};e.default=o}).call(this,n("543d")["default"])},9414:function(t,e,n){},d2dc:function(t,e,n){"use strict";n.r(e);var r=n("0e0a"),a=n.n(r);for(var o in r)"default"!==o&&function(t){n.d(e,t,(function(){return r[t]}))}(o);e["default"]=a.a},e530:function(t,e,n){"use strict";var r,a=function(){var t=this,e=t.$createElement;t._self._c},o=[];n.d(e,"b",(function(){return a})),n.d(e,"c",(function(){return o})),n.d(e,"a",(function(){return r}))},e663:function(t,e,n){"use strict";n.r(e);var r=n("e530"),a=n("d2dc");for(var o in a)"default"!==o&&function(t){n.d(e,t,(function(){return a[t]}))}(o);n("f11c");var u,c=n("f0c5"),i=Object(c["a"])(a["default"],r["b"],r["c"],!1,null,"487050c0",null,!1,r["a"],u);e["default"]=i.exports},f11c:function(t,e,n){"use strict";var r=n("9414"),a=n.n(r);a.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'superuser/userinfo/userContent/userContent-create-component',
    {
        'superuser/userinfo/userContent/userContent-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("e663"))
        })
    },
    [['superuser/userinfo/userContent/userContent-create-component']]
]);
