(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/goodsItem/footer/footer"],{"390c":function(t,e,a){},"9dcd7":function(t,e,a){"use strict";var n,r=function(){var t=this,e=t.$createElement;t._self._c},u=[];a.d(e,"b",(function(){return r})),a.d(e,"c",(function(){return u})),a.d(e,"a",(function(){return n}))},b1d5:function(t,e,a){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;getApp();var a={data:function(){return{background:t.getStorageSync("background"),propertyFlag:!1,flag:0,timeout:!1}},components:{},props:{goodstype:{type:Number},property:{type:Array},price:{type:Number,default:0},group_price:{type:Number,default:0},data:{type:Object}},watch:{data:{handler:function(t){1==t.is_bargain&&t.bargain_end_time&&(new Date).getTime()<Number(1e3*t.bargain_end_time)&&this.setData({timeout:!0})},immediate:!0,deep:!0}},methods:{goIndex:function(){wx.redirectTo({url:"/pages/index/index/index"})},addGoodsShop:function(){this.$emit("show",{detail:{status:"add"}})},toBuy:function(t){this.$emit("show",{detail:{status:t.currentTarget.dataset.status}})},goKefu:function(){wx.navigateTo({url:"/pages/webview/webview"})},toGroupBuy:function(){1==this.property.length?(console.log(this.property[0]),this.$emit("show",{detail:{status:"buy",tuanNum:this.property[0],submit_type:1}})):this.setData({propertyFlag:!0})},change:function(t){this.setData({flag:t.currentTarget.dataset.index,propertyFlag:!1}),this.$emit("show",{detail:{status:"buy",tuanNum:this.data.property[t.currentTarget.dataset.index],submit_type:1}})},close:function(){this.setData({propertyFlag:!1})}}};e.default=a}).call(this,a("543d")["default"])},b455:function(t,e,a){"use strict";a.r(e);var n=a("b1d5"),r=a.n(n);for(var u in n)"default"!==u&&function(t){a.d(e,t,(function(){return n[t]}))}(u);e["default"]=r.a},df0e:function(t,e,a){"use strict";var n=a("390c"),r=a.n(n);r.a},e718:function(t,e,a){"use strict";a.r(e);var n=a("9dcd7"),r=a("b455");for(var u in r)"default"!==u&&function(t){a.d(e,t,(function(){return r[t]}))}(u);a("df0e");var i,o=a("f0c5"),s=Object(o["a"])(r["default"],n["b"],n["c"],!1,null,"6e91acf3",null,!1,n["a"],i);e["default"]=s.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/goodsItem/footer/footer-create-component',
    {
        'pages/goodsItem/footer/footer-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("e718"))
        })
    },
    [['pages/goodsItem/footer/footer-create-component']]
]);
