(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/goodsItem/image/image"],{"092b":function(t,e,a){"use strict";a.r(e);var n=a("35c5"),i=a("7d35");for(var o in i)"default"!==o&&function(t){a.d(e,t,(function(){return i[t]}))}(o);a("4c8e");var r,s=a("f0c5"),u=Object(s["a"])(i["default"],n["b"],n["c"],!1,null,"0e2ee256",null,!1,n["a"],r);e["default"]=u.exports},"35c5":function(t,e,a){"use strict";var n,i=function(){var t=this,e=t.$createElement;t._self._c},o=[];a.d(e,"b",(function(){return i})),a.d(e,"c",(function(){return o})),a.d(e,"a",(function(){return n}))},"4c8e":function(t,e,a){"use strict";var n=a("ec30"),i=a.n(n);i.a},"7d35":function(t,e,a){"use strict";a.r(e);var n=a("a323"),i=a.n(n);for(var o in n)"default"!==o&&function(t){a.d(e,t,(function(){return n[t]}))}(o);e["default"]=i.a},a323:function(t,e,a){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n,i=a("1be5"),o={data:function(){return{shareFlag:!1,is_open:!1,autoplay:!0,timeout:!0,day:"",hour:"",minute:"",second:""}},components:{},props:{data:{type:Object},interFlag:{type:Boolean}},watch:{data:{handler:function(t){var e=this;if(1==t.is_flash_sale){var a=1e3*t.start_time<(new Date).getTime()?1e3*t.end_time:1e3*t.start_time,o=1e3*t.start_time<(new Date).getTime()?"仅剩dd天hh时mm分ss秒":"dd天hh时mm分ss秒后开始";this.setData({countdown:(0,i.timeStamp)(a,o)}),n=setInterval((function(){e.setData({countdown:(0,i.timeStamp)(a,o)})}),1e3)}1==t.is_bargain&&t.bargain_end_time&&1e3*t.bargain_end_time>(new Date).getTime()?(this.simpodataformart(t.bargain_end_time),setInterval((function(){e.simpodataformart(t.bargain_end_time)}),1e3)):this.setData({timeout:!1})},immediate:!0,deep:!0},interFlag:{handler:function(t){t&&clearInterval(n)},immediate:!0}},beforeMount:function(){this.setData({is_open:t.getStorageSync("Config").is_stock})},methods:{goCart:function(){wx.navigateTo({url:"/pages/shopCart/shopCart/shopCart"})},showShare:function(){this.$emit("showShare")},toshare:function(){wx.navigateTo({url:"/pages/share/share?id=".concat(this.data.goodsid)})},move:function(){return!1},changeswiper:function(){this.setData({autoplay:!1})},simpodataformart:function(t){var e=parseInt((1e3*t-(new Date).getTime())/1e3),a=parseInt(e/86400).toString().padStart(2,0),n=parseInt(e%86400/3600).toString().padStart(2,0),i=parseInt(e%3600/60).toString().padStart(2,0),o=parseInt(e%60).toString().padStart(2,0);this.setData({day:a,hour:n,minute:i,second:o,timeout:!0}),console.log(e,this.timeout)}}};e.default=o}).call(this,a("543d")["default"])},ec30:function(t,e,a){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/goodsItem/image/image-create-component',
    {
        'pages/goodsItem/image/image-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("092b"))
        })
    },
    [['pages/goodsItem/image/image-create-component']]
]);
