(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/goodsItem/goodsCoupons/goodsCoupons"],{"01d7":function(t,o,n){"use strict";var e,a=function(){var t=this,o=t.$createElement;t._self._c},r=[];n.d(o,"b",(function(){return a})),n.d(o,"c",(function(){return r})),n.d(o,"a",(function(){return e}))},"6c1c":function(t,o,n){"use strict";n.r(o);var e=n("add8"),a=n.n(e);for(var r in e)"default"!==r&&function(t){n.d(o,t,(function(){return e[t]}))}(r);o["default"]=a.a},7231:function(t,o,n){"use strict";var e=n("b464"),a=n.n(e);a.a},add8:function(t,o,n){"use strict";(function(t){function n(t){return c(t)||r(t)||a(t)||e()}function e(){throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}function a(t,o){if(t){if("string"===typeof t)return u(t,o);var n=Object.prototype.toString.call(t).slice(8,-1);return"Object"===n&&t.constructor&&(n=t.constructor.name),"Map"===n||"Set"===n?Array.from(n):"Arguments"===n||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)?u(t,o):void 0}}function r(t){if("undefined"!==typeof Symbol&&Symbol.iterator in Object(t))return Array.from(t)}function c(t){if(Array.isArray(t))return u(t)}function u(t,o){(null==o||o>t.length)&&(o=t.length);for(var n=0,e=new Array(o);n<o;n++)e[n]=t[n];return e}Object.defineProperty(o,"__esModule",{value:!0}),o.default=void 0;getApp();var i={data:function(){return{background:"",fontcolor:"",couponsData:[],layerFlag:!1,goodsCoupons:{},reduction:{}}},components:{},props:{data:{type:Object}},watch:{data:{handler:function(t){t.hasOwnProperty("id")&&0==t.is_advance_sale&&(this.getGoodsCoupons(t.id),this.getData())},immediate:!0,deep:!0}},beforeMount:function(){this.setData({background:t.getStorageSync("background"),fontcolor:t.getStorageSync("nabigationFontColor")})},methods:{getData:function(){var o=this;this.http({url:"ShopRedEnvelope",data:{key:t.getStorageSync("shopkey"),type:1}}).then((function(e){o.setData({couponsData:[].concat(n(o.couponsData),n(e.data)),reduction:t.getStorageSync("Config").reduction_info})}))},getGoodsCoupons:function(o){var e=this;this.http({url:"ShopRedEnvelope",data:{key:t.getStorageSync("shopkey"),goods_id:o}}).then((function(t){e.setData({goodsCoupons:t.data[0],couponsData:[].concat(n(e.couponsData),n(t.data))})}))},couponsShow:function(){this.setData({layerFlag:!this.layerFlag})},getCoupons:function(t){this.http({url:"ShopRedEnvelope",method:"post",data:{type_id:t.currentTarget.dataset.id}}).then((function(t){wx.showToast({title:"领取成功",icon:"success",duration:2e3})}))}}};o.default=i}).call(this,n("543d")["default"])},b464:function(t,o,n){},d6bb:function(t,o,n){"use strict";n.r(o);var e=n("01d7"),a=n("6c1c");for(var r in a)"default"!==r&&function(t){n.d(o,t,(function(){return a[t]}))}(r);n("7231");var c,u=n("f0c5"),i=Object(u["a"])(a["default"],e["b"],e["c"],!1,null,"b3c1569a",null,!1,e["a"],c);o["default"]=i.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/goodsItem/goodsCoupons/goodsCoupons-create-component',
    {
        'pages/goodsItem/goodsCoupons/goodsCoupons-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("d6bb"))
        })
    },
    [['pages/goodsItem/goodsCoupons/goodsCoupons-create-component']]
]);
