(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["promoter/promoteOrder/promoteOrderList/promoteOrderList"],{1504:function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n={data:function(){return{List:[{order_sn:"123456879",status:"代发货",pic_url:"/static/images/clockIn/b.png",content:"日日做着同样的事情,循环着与昨日相同的惯例,若能避开猛烈的狂喜,自然不会有悲痛来袭",price:"0.01",nums:"1",avatar:t.getStorageSync("avatar"),nickname:"咸鱼康",phone:"15195729049",remark:"配送到家 谢谢",price2:"1000.00",pay:"1000.00"}],groupid:t.getStorageSync("user").id}},components:{},props:{data:{type:Array,default:function(){return[]}}},methods:{call:function(e){t.getStorageSync("user").is_self&&wx.makePhoneCall({phoneNumber:e.currentTarget.dataset.phone})},go:function(t){wx.navigateTo({url:"/pages/payOk/payOk/payOk?order_sn=".concat(t.currentTarget.dataset.order_sn)})},tuanReceiving:function(e){var n=this;t.getStorageSync("user").is_self?this.http({url:"tuanReceiving",method:"put",data:{order_sn:e.currentTarget.dataset.order_sn}}).then((function(t){wx.showToast({title:"收货成功",icon:"none"}),n.$emit("deleteData",{detail:{index:e.currentTarget.dataset.index}})})).catch((function(t){})):wx.showToast({title:"暂无操作权限",icon:"none"})},tuanConfirm:function(e){var n=this;t.getStorageSync("user").is_self?this.http({url:"tuanConfirm",method:"put",data:{order_sn:e.currentTarget.dataset.order_sn}}).then((function(t){wx.showToast({title:"核销成功",icon:"none"}),n.$emit("deleteData",{detail:{index:e.currentTarget.dataset.index}})})).catch((function(t){})):wx.showToast({title:"暂无操作权限",icon:"none"})}}};e.default=n}).call(this,n("543d")["default"])},"3ee6":function(t,e,n){"use strict";n.r(e);var r=n("1504"),a=n.n(r);for(var o in r)"default"!==o&&function(t){n.d(e,t,(function(){return r[t]}))}(o);e["default"]=a.a},"6b04":function(t,e,n){},"77f9":function(t,e,n){"use strict";var r,a=function(){var t=this,e=t.$createElement;t._self._c},o=[];n.d(e,"b",(function(){return a})),n.d(e,"c",(function(){return o})),n.d(e,"a",(function(){return r}))},b75f:function(t,e,n){"use strict";n.r(e);var r=n("77f9"),a=n("3ee6");for(var o in a)"default"!==o&&function(t){n.d(e,t,(function(){return a[t]}))}(o);n("c67a");var i,c=n("f0c5"),u=Object(c["a"])(a["default"],r["b"],r["c"],!1,null,"39a14f80",null,!1,r["a"],i);e["default"]=u.exports},c67a:function(t,e,n){"use strict";var r=n("6b04"),a=n.n(r);a.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'promoter/promoteOrder/promoteOrderList/promoteOrderList-create-component',
    {
        'promoter/promoteOrder/promoteOrderList/promoteOrderList-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("b75f"))
        })
    },
    [['promoter/promoteOrder/promoteOrderList/promoteOrderList-create-component']]
]);
