(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/integralMall/createOrder/layer/layer"],{"04e1":function(t,e,n){"use strict";n.r(e);var r=n("6265"),o=n.n(r);for(var a in r)"default"!==a&&function(t){n.d(e,t,(function(){return r[t]}))}(a);e["default"]=o.a},"0863":function(t,e,n){},"2c3f":function(t,e,n){"use strict";var r=n("0863"),o=n.n(r);o.a},"51b2":function(t,e,n){"use strict";var r,o=function(){var t=this,e=t.$createElement;t._self._c;t._isMounted||(t.e0=function(t){return t.stopPropagation(),(!1)(t)},t.e1=function(t){return t.stopPropagation(),(!1)(t)},t.e2=function(t){return t.stopPropagation(),(!1)(t)},t.e3=function(t){return t.stopPropagation(),(!1)(t)})},a=[];n.d(e,"b",(function(){return o})),n.d(e,"c",(function(){return a})),n.d(e,"a",(function(){return r}))},6265:function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n={data:function(){return{status:0}},components:{},props:{show:{type:Boolean,default:!0},score:{type:Number,default:0},data:{type:Object},addressid:{type:Number},goodsScore:{type:String}},methods:{yes:function(e){var n=this;console.log(this),Number(this.data.score)>t.getStorageSync("user").score?this.setData({status:2}):this.http({url:"shopScoreOrder",method:"post",data:{score_goods_id:this.data.id,user_contact_id:this.addressid}}).then((function(t){n.setData({status:1})})).catch((function(t){"库存不足"==t.data.message&&n.setData({status:3})}))},ok:function(t){wx.redirectTo({url:"../../order/order"})},err:function(t){wx.redirectTo({url:"/pages/index/index/index"})},show:function(){this.$emit("show",{detail:{}}),this.setData({status:0})}}};e.default=n}).call(this,n("543d")["default"])},9605:function(t,e,n){"use strict";n.r(e);var r=n("51b2"),o=n("04e1");for(var a in o)"default"!==a&&function(t){n.d(e,t,(function(){return o[t]}))}(a);n("2c3f");var s,u=n("f0c5"),i=Object(u["a"])(o["default"],r["b"],r["c"],!1,null,"9c299cb4",null,!1,r["a"],s);e["default"]=i.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/integralMall/createOrder/layer/layer-create-component',
    {
        'pages/integralMall/createOrder/layer/layer-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("9605"))
        })
    },
    [['pages/integralMall/createOrder/layer/layer-create-component']]
]);
