(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/createOrder/coupons/coupons"],{"0138":function(e,t,n){},"0142":function(e,t,n){"use strict";n.r(t);var o=n("05a0"),i=n.n(o);for(var a in o)"default"!==a&&function(e){n.d(t,e,(function(){return o[e]}))}(a);t["default"]=i.a},"05a0":function(e,t,n){"use strict";(function(e){Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;getApp();var n={data:function(){return{coupone:"",couponeList:"",show:!1,discount_ratio:0,is_vip:!1,leader_discount:0,goodsPrice:0,youfei:0,is_reduction:!1,reduction_achieve:"",reduction_decrease:0,free_shipping:!1,free_flag:!1,free_data:[]}},components:{},props:{supplier_id:{type:Number,default:-1},discount:{type:Object},goodsData:{type:Array,default:function(){return[]}},shopindex:{type:Number},ajaxshow:{type:Boolean},user_contact_id:{type:Number}},watch:{discount:{handler:function(e){console.log(e)}},supplier_id:{handler:function(e){this.gethongbao(e,this.goodsData.map((function(e){return e.goods_id})).join(","))},immediate:!0},goodsData:{handler:function(e){var t=e.map((function(e){return e.price*e.number})).reduce((function(e,t,n){return Number(e)+Number(t)}));this.setData({goodsPrice:t})},immediate:!0,deep:!0}},mounted:function(){this.free_data=wx.getStorageSync("Config").reduction_info;var t=e.getStorageSync("Config").reduction_info;1==t.is_reduction&&this.setData({is_reduction:!0})},methods:{gethongbao:function(e,t){var n=this;this.http({url:"ShopVoucherSupplier",data:{supplier_id:e,goods_id:t}}).then((function(e){n.setData({couponeList:e.data})}))},showLayer:function(){this.setData({show:!0})},closeLayer:function(e){this.setData({show:!1,coupone:this.couponeList[e.currentTarget.dataset.index]}),this.$emit("setVoucher_id",{detail:{index:this.shopindex,coupone:this.coupone}})},nocpuponce:function(){this.setData({coupone:{is_used:2},show:!1}),this.$emit("coupone",{detail:{is_used:2,price:0,full_price:0}})},remark:function(e){this.$emit("remark",{detail:{index:this.shopindex,data:e.detail.value}})},closefree_shopinglayer:function(){this.setData({free_flag:!this.free_flag})}}};t.default=n}).call(this,n("543d")["default"])},"3e46":function(e,t,n){"use strict";var o,i=function(){var e=this,t=e.$createElement;e._self._c},a=[];n.d(t,"b",(function(){return i})),n.d(t,"c",(function(){return a})),n.d(t,"a",(function(){return o}))},"53dc":function(e,t,n){"use strict";n.r(t);var o=n("3e46"),i=n("0142");for(var a in i)"default"!==a&&function(e){n.d(t,e,(function(){return i[e]}))}(a);n("804b");var u,r=n("f0c5"),c=Object(r["a"])(i["default"],o["b"],o["c"],!1,null,"18f97c42",null,!1,o["a"],u);t["default"]=c.exports},"804b":function(e,t,n){"use strict";var o=n("0138"),i=n.n(o);i.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/createOrder/coupons/coupons-create-component',
    {
        'pages/createOrder/coupons/coupons-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("53dc"))
        })
    },
    [['pages/createOrder/coupons/coupons-create-component']]
]);
