(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["superuser/superuserorder/superuserorderList/superuserorderList"],{"100a":function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n={data:function(){return{List:[{order_sn:"123456879",status:"代发货",pic_url:"/static/images/clockIn/b.png",content:"日日做着同样的事情,循环着与昨日相同的惯例,若能避开猛烈的狂喜,自然不会有悲痛来袭",price:"0.01",nums:"1",avatar:t.getStorageSync("avatar"),nickname:"咸鱼康",phone:"15195729049",remark:"配送到家 谢谢",price2:"1000.00",pay:"1000.00"}],groupid:t.getStorageSync("user").id}},components:{},props:{data:{type:Array,default:function(){return[]}},status:{type:"Number",default:2}},methods:{call:function(e){t.getStorageSync("user").is_self&&wx.makePhoneCall({phoneNumber:e.currentTarget.dataset.phone})},go:function(t){wx.navigateTo({url:"/pages/payOk/payOk/payOk?order_sn=".concat(t.currentTarget.dataset.order_sn)})},tuanReceiving:function(e){var n=this;t.getStorageSync("user").is_self?this.http({url:"tuanReceiving",method:"put",data:{order_sn:e.currentTarget.dataset.order_sn}}).then((function(t){wx.showToast({title:"收货成功",icon:"none"}),n.$emit("deleteData",{detail:{index:e.currentTarget.dataset.index}})})).catch((function(t){})):wx.showToast({title:"暂无操作权限",icon:"none"})},tuanConfirm:function(e){var n=this;t.getStorageSync("user").is_self?this.http({url:"tuanConfirm",method:"put",data:{order_sn:e.currentTarget.dataset.order_sn}}).then((function(t){wx.showToast({title:"核销成功",icon:"none"}),n.$emit("deleteData",{detail:{index:e.currentTarget.dataset.index}})})).catch((function(t){})):wx.showToast({title:"暂无操作权限",icon:"none"})}}};e.default=n}).call(this,n("543d")["default"])},"34bf":function(t,e,n){"use strict";var a=n("6a45"),r=n.n(a);r.a},"64ed":function(t,e,n){"use strict";n.r(e);var a=n("7a40"),r=n("ebe8");for(var u in r)"default"!==u&&function(t){n.d(e,t,(function(){return r[t]}))}(u);n("34bf");var o,i=n("f0c5"),s=Object(i["a"])(r["default"],a["b"],a["c"],!1,null,"3c40aa80",null,!1,a["a"],o);e["default"]=s.exports},"6a45":function(t,e,n){},"7a40":function(t,e,n){"use strict";var a,r=function(){var t=this,e=t.$createElement;t._self._c},u=[];n.d(e,"b",(function(){return r})),n.d(e,"c",(function(){return u})),n.d(e,"a",(function(){return a}))},ebe8:function(t,e,n){"use strict";n.r(e);var a=n("100a"),r=n.n(a);for(var u in a)"default"!==u&&function(t){n.d(e,t,(function(){return a[t]}))}(u);e["default"]=r.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'superuser/superuserorder/superuserorderList/superuserorderList-create-component',
    {
        'superuser/superuserorder/superuserorderList/superuserorderList-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("64ed"))
        })
    },
    [['superuser/superuserorder/superuserorderList/superuserorderList-create-component']]
]);
