(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/orderItem/orderItemAddress/orderItemAddress"],{"2bc4":function(e,t,r){"use strict";var n,o=function(){var e=this,t=e.$createElement;e._self._c},a=[];r.d(t,"b",(function(){return o})),r.d(t,"c",(function(){return a})),r.d(t,"a",(function(){return n}))},53927:function(e,t,r){"use strict";r.r(t);var n=r("2bc4"),o=r("8d2f");for(var a in o)"default"!==a&&function(e){r.d(t,e,(function(){return o[e]}))}(a);r("5e9d");var s,u=r("f0c5"),c=Object(u["a"])(o["default"],n["b"],n["c"],!1,null,"8da341e6",null,!1,n["a"],s);t["default"]=c.exports},"5e9d":function(e,t,r){"use strict";var n=r("a6ea"),o=r.n(n);o.a},"8d2f":function(e,t,r){"use strict";r.r(t);var n=r("91b6"),o=r.n(n);for(var a in n)"default"!==a&&function(e){r.d(t,e,(function(){return n[e]}))}(a);t["default"]=o.a},"91b6":function(e,t,r){"use strict";(function(e){function r(e,t){var r=Object.keys(e);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(e);t&&(n=n.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),r.push.apply(r,n)}return r}function n(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?r(Object(n),!0).forEach((function(t){o(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):r(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function o(e,t,r){return t in e?Object.defineProperty(e,t,{value:r,enumerable:!0,configurable:!0,writable:!0}):e[t]=r,e}Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a={data:function(){return{address:{}}},computed:{express_typefmt:function(){var e={0:"快递发货",1:"到点自提",2:"团长配送"};return e[this.express_type]}},components:{},props:{addressData:{type:Object},express_type:{type:String},group_address:{type:Object}},watch:{addressData:{handler:function(e){console.log(e),this.setData({address:n({},e,{address:e.address.slice(0,e.address.length-7)})})},immediate:!0,deep:!0}},methods:{toPhone:function(){e.makePhoneCall({phoneNumber:this.group_address.phone})},getlocation:function(t){e.openLocation({latitude:Number(this.group_address.latitude),longitude:Number(this.group_address.longitude)})}}};t.default=a}).call(this,r("543d")["default"])},a6ea:function(e,t,r){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/orderItem/orderItemAddress/orderItemAddress-create-component',
    {
        'pages/orderItem/orderItemAddress/orderItemAddress-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("53927"))
        })
    },
    [['pages/orderItem/orderItemAddress/orderItemAddress-create-component']]
]);
